---
# Source: nodeport-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-release-nodeport-service
  labels:
    helm.sh/chart: nodeport-service-0.1.0
    app.kubernetes.io/name: nodeport-service
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
# added the below for NodePort
      # nodePort only included when service type == NodePort
      nodePort: 30080
  selector:
    app.kubernetes.io/name: nodeport-service
    app.kubernetes.io/instance: my-release
---
# Source: nodeport-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-release-nodeport-service
  labels:
    helm.sh/chart: nodeport-service-0.1.0
    app.kubernetes.io/name: nodeport-service
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nodeport-service
      app.kubernetes.io/instance: my-release
  template:
    metadata:
      labels:
        helm.sh/chart: nodeport-service-0.1.0
        app.kubernetes.io/name: nodeport-service
        app.kubernetes.io/instance: my-release
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: default
      containers:
        - name: nodeport-service
          image: "nginx:alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
# Source: nodeport-service/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "my-release-nodeport-service-test-connection"
  labels:
    helm.sh/chart: nodeport-service-0.1.0
    app.kubernetes.io/name: nodeport-service
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['my-release-nodeport-service:80']
  restartPolicy: Never
