apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodeport-service.fullname" . }}
  labels:
    {{- include "nodeport-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
# added the below for NodePort
{{- if eq .Values.service.type "NodePort" }}
      # nodePort only included when service type == NodePort
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    {{- include "nodeport-service.selectorLabels" . | nindent 4 }}
